#!/usr/bin/env python3
"""Exact PSD-atom Farkas certificates for arbitrary normalized-K bases.

Unlike a required-clique basis, an arbitrary principal basis has no
Sherman--Morrison coordinates.  Its inverse ``H`` is nevertheless positive
definite and obeys affine Schur equations.  This module searches a restricted
rational semidefinite dual cone generated by ``v v^T`` for small integer
vectors ``v``.  Floating-point LP is only a locator; every returned
certificate is checked over ``Fraction``.

The exact alternative allows ``Q=0`` when a nonzero multiplier of a strict
outside-diagonal inequality already gives a contradiction.  Its required
nontriviality condition is ``(Q, lambda) != (0, 0)``, enforced here by
normalizing the sum of PSD-atom weights and strict multipliers to one.

This module certifies that one specified subset cannot be a principal basis.
It does *not* reject a cover unless every possible basis size and subset has
been eliminated.
"""

from __future__ import annotations

import itertools
from dataclasses import dataclass
from fractions import Fraction
from typing import Sequence

import d6_k7_positive_polynomial_dual as exact
import d6_k7_special_h_reference as href


Q = Fraction


@dataclass(frozen=True)
class BasisAffineSystem:
    rank: int
    core: tuple[int, ...]
    remainder: tuple[int, ...]
    columns: tuple[tuple[int, ...], ...]
    equation_pairs: tuple[tuple[int, int], ...]
    equation_rows: tuple[tuple[Q, ...], ...]
    equation_rhs: tuple[Q, ...]
    diagonal_rows: tuple[tuple[Q, ...], ...]


def basis_affine_system(
    adj: Sequence[int], core: Sequence[int]
) -> BasisAffineSystem:
    """Build necessary affine equations for a proposed principal basis."""

    core = tuple(int(vertex) for vertex in core)
    if len(set(core)) != len(core) or not core:
        raise ValueError("core must contain distinct vertices")
    if any(not 0 <= vertex < len(adj) for vertex in core):
        raise ValueError("core vertex is out of range")
    remainder = tuple(vertex for vertex in range(len(adj)) if vertex not in core)
    columns = tuple(
        tuple(int(bool(adj[vertex] & (1 << basis))) for basis in core)
        for vertex in remainder
    )
    pairs: list[tuple[int, int]] = []
    rows: list[tuple[Q, ...]] = []
    rhs: list[Q] = []
    for first, second in itertools.combinations(range(len(remainder)), 2):
        pairs.append((remainder[first], remainder[second]))
        rows.append(href.bilinear_form_coefficients(
            columns[first], columns[second]
        ))
        rhs.append(Q(int(bool(
            adj[remainder[first]] & (1 << remainder[second])
        ))))
    diagonal = tuple(href.quadratic_form_coefficients(column) for column in columns)
    return BasisAffineSystem(
        rank=len(core),
        core=core,
        remainder=remainder,
        columns=columns,
        equation_pairs=tuple(pairs),
        equation_rows=tuple(rows),
        equation_rhs=tuple(rhs),
        diagonal_rows=diagonal,
    )


def atom_vectors(rank: int, maximum_support: int | None = 3) -> tuple[tuple[int, ...], ...]:
    """Primitive representatives of {-1,0,1} vectors modulo sign."""

    return tuple(
        vector
        for vector in itertools.product((-1, 0, 1), repeat=rank)
        if any(vector)
        and next(value for value in vector if value) > 0
        and (
            maximum_support is None
            or sum(value != 0 for value in vector) <= maximum_support
        )
    )


def verify_certificate(system: BasisAffineSystem, certificate: dict) -> None:
    """Check a PSD-atom affine alternative using only rational arithmetic."""

    if certificate.get("core") != list(system.core):
        raise ValueError("certificate core mismatch")
    if certificate.get("equation_pairs") != [
        list(pair) for pair in system.equation_pairs
    ]:
        raise ValueError("certificate equation order mismatch")
    equation_multipliers = [Q(0)] * len(system.equation_rows)
    for item in certificate.get("equation_multipliers", []):
        index = int(item["equation"])
        if not 0 <= index < len(equation_multipliers):
            raise ValueError("equation multiplier index out of range")
        equation_multipliers[index] += exact.parse_fraction(item["value"])
    lambdas = [Q(0)] * len(system.diagonal_rows)
    for item in certificate.get("diagonal_multipliers", []):
        index = int(item["remainder_index"])
        if not 0 <= index < len(lambdas):
            raise ValueError("diagonal multiplier index out of range")
        value = exact.parse_fraction(item["value"])
        if value < 0:
            raise ValueError("negative strict-inequality multiplier")
        lambdas[index] += value
    atoms: list[tuple[tuple[int, ...], Q]] = []
    for item in certificate.get("psd_atoms", []):
        vector = tuple(int(value) for value in item["vector"])
        if len(vector) != system.rank or not any(vector):
            raise ValueError("invalid PSD atom")
        weight = exact.parse_fraction(item["weight"])
        if weight < 0:
            raise ValueError("negative PSD-atom weight")
        atoms.append((vector, weight))
    slack = exact.parse_fraction(certificate["scalar_slack"])
    if slack < 0:
        raise ValueError("negative scalar slack")
    if sum(lambdas) + sum(weight for _, weight in atoms) != 1:
        raise ValueError("certificate normalization is not one")

    width = system.rank * (system.rank + 1) // 2
    left = [Q(0)] * width
    for multiplier, row in zip(equation_multipliers, system.equation_rows):
        left = [a + multiplier * b for a, b in zip(left, row)]
    for multiplier, row in zip(lambdas, system.diagonal_rows):
        left = [a - multiplier * b for a, b in zip(left, row)]
    right = [Q(0)] * width
    for vector, weight in atoms:
        row = href.quadratic_form_coefficients(vector)
        right = [a + weight * b for a, b in zip(right, row)]
    if left != right:
        raise ValueError("PSD matrix identity does not check")
    scalar = sum(
        multiplier * value
        for multiplier, value in zip(equation_multipliers, system.equation_rhs)
    ) - sum(lambdas) + slack
    if scalar:
        raise ValueError("dual scalar inequality does not check")


def find_certificate(
    system: BasisAffineSystem,
    maximum_atom_support: int | None = 3,
) -> dict | None:
    """Locate and exactly reconstruct a restricted PSD dual certificate."""

    try:
        import numpy as np
        from scipy.optimize import linprog
    except ImportError:
        return None
    atoms = atom_vectors(system.rank, maximum_atom_support)
    atom_rows = tuple(href.quadratic_form_coefficients(vector) for vector in atoms)
    equality_count = len(system.equation_rows)
    diagonal_count = len(system.diagonal_rows)
    atom_count = len(atoms)
    width = system.rank * (system.rank + 1) // 2
    variables = equality_count + diagonal_count + atom_count + 1
    matrix = [[Q(0)] * variables for _ in range(width + 2)]
    rhs = [Q(0)] * (width + 2)
    for index, row in enumerate(system.equation_rows):
        for coordinate, value in enumerate(row):
            matrix[coordinate][index] = value
    for index, row in enumerate(system.diagonal_rows):
        column = equality_count + index
        for coordinate, value in enumerate(row):
            matrix[coordinate][column] = -value
    for index, row in enumerate(atom_rows):
        column = equality_count + diagonal_count + index
        for coordinate, value in enumerate(row):
            matrix[coordinate][column] = -value

    scalar_row = width
    for index, value in enumerate(system.equation_rhs):
        matrix[scalar_row][index] = value
    for index in range(diagonal_count):
        matrix[scalar_row][equality_count + index] = Q(-1)
    matrix[scalar_row][-1] = Q(1)  # nonnegative slack
    normalization_row = width + 1
    for index in range(diagonal_count + atom_count):
        matrix[normalization_row][equality_count + index] = Q(1)
    rhs[normalization_row] = Q(1)

    numeric = np.asarray(matrix, dtype=float)
    result = linprog(
        np.zeros(variables),
        A_eq=numeric,
        b_eq=np.asarray(rhs, dtype=float),
        bounds=(
            [(None, None)] * equality_count
            + [(0, None)] * (diagonal_count + atom_count + 1)
        ),
        method="highs-ds",
    )
    if not result.success or result.x is None:
        return None

    constrained_start = equality_count
    for cutoff in (1e-7, 1e-9, 1e-11, 1e-13):
        zero_rows: list[list[Q]] = []
        for column in range(constrained_start, variables):
            if result.x[column] <= cutoff:
                row = [Q(0)] * variables
                row[column] = Q(1)
                zero_rows.append(row)
        affine = href.exact_rref(
            list(matrix) + zero_rows,
            rhs + [Q(0)] * len(zero_rows),
            variables,
        )
        if not affine.consistent:
            continue
        for denominator in (1_000, 1_000_000, 1_000_000_000):
            point = exact._guided_rational_point(affine, result.x, denominator)
            if any(value < 0 for value in point[constrained_start:]):
                continue
            equation_values = point[:equality_count]
            lambda_values = point[
                equality_count:equality_count + diagonal_count
            ]
            atom_values = point[
                equality_count + diagonal_count:
                equality_count + diagonal_count + atom_count
            ]
            certificate = {
                "schema": 1,
                "kind": "arbitrary_basis_psd_atom_farkas",
                "core": list(system.core),
                "remainder": list(system.remainder),
                "equation_pairs": [list(pair) for pair in system.equation_pairs],
                "equation_multipliers": [
                    {"equation": index, "value": exact.fraction_json(value)}
                    for index, value in enumerate(equation_values) if value
                ],
                "diagonal_multipliers": [
                    {
                        "remainder_index": index,
                        "vertex": system.remainder[index],
                        "value": exact.fraction_json(value),
                    }
                    for index, value in enumerate(lambda_values) if value
                ],
                "psd_atoms": [
                    {
                        "vector": list(atoms[index]),
                        "weight": exact.fraction_json(value),
                    }
                    for index, value in enumerate(atom_values) if value
                ],
                "scalar_slack": exact.fraction_json(point[-1]),
            }
            verify_certificate(system, certificate)
            return certificate
    return None


def find_basis_certificate(
    adj: Sequence[int],
    core: Sequence[int],
    maximum_atom_support: int | None = 3,
) -> dict | None:
    system = basis_affine_system(adj, core)
    return find_certificate(system, maximum_atom_support)
