#!/usr/bin/env python3
"""Certified kill campaign for f(5): decide non-realizability in R^5 of the
minimal abstract almost-equidistant graphs on 17..20 vertices.

Top-down schedule (each completed level is a theorem):
  level 20 (8 graphs)    killed  =>  f(5) <= 19
  level 19 (340)         killed  =>  f(5) <= 18
  level 18 (8825)        killed  =>  f(5) <= 17
  level 17 (12654)       killed  =>  f(5) =  16   (with the 16-point set)

Usage:
  python reproduce5.py --controls
  python reproduce5.py --level 20 [--graph i] [--workers N]

Graph files aeq_d5_nXX.txt: one graph per line, "n mask0 ... mask{n-1}"
(complements of maximal triangle-free graphs, alpha<=2, no K7, no K333;
generated by triangleramsey + filter_mtf, counts matching BPSSV Table 2).
"""
import argparse, json, math, os, sys, time
from multiprocessing import Pool, cpu_count

from cdriver5 import decide5, gen_orders, ensure_kernel

TWO_PI = 2 * math.pi
HERE = os.path.dirname(os.path.abspath(__file__))
os.chdir(HERE)

def load_level(level):
    graphs = []
    with open(f"aeq_d5_n{level}.txt") as f:
        for line in f:
            parts = line.split()
            if not parts: continue
            n = int(parts[0]); assert n == level
            graphs.append([int(x) for x in parts[1:1 + n]])
    return graphs

# ---------------------------------------------------------------------------
_DATA = {}
def _slice_task(args):
    global _DATA
    level, gi, seed, order, lo, hi, cap = args
    if level not in _DATA:
        _DATA[level] = load_level(level)
    adj = _DATA[level][gi]
    st, nodes, unres = decide5(adj, level, seed=seed, order=list(order),
                               th0=(lo, hi), max_nodes=cap)
    return lo, hi, st, nodes

def ncirc_of(adj, n, seed, order):
    placed = set(seed); c = 0
    for v in order:
        if sum(1 for u in placed if (adj[v] >> u) & 1) == 4: c += 1
        placed.add(v)
    return c

def certify_graph(level, gi, adj, pool, max_orders=12, cap=15_000_000,
                  budget_s=7200, fine=False, verbose=False):
    """Race decompositions concurrently; 8-fold split failed slices; a fully
    killed tiling certifies. Returns winning decomposition index or None."""
    import queue
    decs = gen_orders(adj, level, kmax=max_orders)
    if not decs:
        return None
    Q = queue.Queue()
    state = [{"pending": 0, "alive": True, "submitted": False} for _ in decs]
    nc0 = ncirc_of(adj, level, *decs[0])
    nslices = 768 if nc0 >= 2 else (24 if nc0 == 1 else 1)
    min_width = TWO_PI / max(nslices, 24) / 8 ** 3

    ncircs = [ncirc_of(adj, level, *d) for d in decs]

    def submit_range(oi, lo, hi):
        seed, order = decs[oi]
        state[oi]["pending"] += 1
        # circle-free searches get one task with a much larger budget
        # (there is no slicing dimension; only nodes help)
        c = cap * 40 if ncircs[oi] == 0 else cap
        pool.apply_async(_slice_task,
                         ((level, gi, seed, tuple(order), lo, hi, c),),
                         callback=lambda r, oi=oi: Q.put((oi, r)),
                         error_callback=lambda e, oi=oi: Q.put((oi, e)))

    ns1 = 384 if fine else 24     # fine initial slicing: the dominant
    for oi in range(len(decs)):   # accelerator for stubborn graphs (d=4)
        state[oi]["submitted"] = True
        nc = ncircs[oi]
        ns = 768 if nc >= 2 else (ns1 if nc == 1 else 1)
        for k in range(ns):
            submit_range(oi, k * TWO_PI / ns, (k + 1) * TWO_PI / ns)
    deadline = time.time() + budget_s
    while True:
        alive = [oi for oi, s in enumerate(state) if s["alive"]]
        if not alive:
            return None
        for oi in alive:
            if state[oi]["submitted"] and state[oi]["pending"] == 0:
                return oi
        if time.time() > deadline:
            return None
        try:
            oi, r = Q.get(timeout=30)
        except Exception:
            continue
        s = state[oi]
        s["pending"] -= 1
        if isinstance(r, Exception):
            s["alive"] = False
        else:
            lo, hi, st, nodes = r
            if s["alive"] and st != "KILLED":
                if ncircs[oi] == 0 or hi - lo < min_width * 8:
                    s["alive"] = False   # no slicing dimension / width floor
                else:
                    w = (hi - lo) / 8
                    for k in range(8):
                        submit_range(oi, lo + k * w, lo + (k + 1) * w)

# ---------------------------------------------------------------------------
def _bulk_task(args):
    """Phase A: one full search on the first decomposition (must be
    circle-free for a single task to be a complete certificate)."""
    global _DATA
    level, gi, cap = args
    if level not in _DATA:
        _DATA[level] = load_level(level)
    adj = _DATA[level][gi]
    decs = gen_orders(adj, level, kmax=1)
    if not decs:
        return gi, "NOORDER", 0
    seed, order = decs[0]
    if ncirc_of(adj, level, seed, order) != 0:
        return gi, "HASCIRCLE", 0
    st, nodes, unres = decide5(adj, level, seed=seed, order=order,
                               max_nodes=cap)
    return gi, st, nodes

def bulk_certify(level, graphs, pool, results, cap=10_000_000):
    """Certify all zero-circle graphs with one shared pool (one task per
    graph — a KILLED unrestricted search on one order is a complete
    certificate). Returns list of graphs needing phase B."""
    todo = [gi for gi in range(len(graphs))
            if results.get(gi) is None]
    print(f"phase A: {len(todo)} graphs, single-task bulk", flush=True)
    t0 = time.time()
    phase_b = []
    done = 0
    for gi, st, nodes in pool.imap_unordered(
            _bulk_task, [(level, gi, cap) for gi in todo], chunksize=8):
        done += 1
        if st == "KILLED":
            results[gi] = 0
        else:
            phase_b.append(gi)
        if done % 1000 == 0 or done == len(todo):
            print(f"  bulk {done}/{len(todo)} killed={done-len(phase_b)} "
                  f"deferred={len(phase_b)} t={time.time()-t0:.0f}s",
                  flush=True)
    return phase_b

def _control_slice(args):
    which, lo, hi, theta_min, cap = args
    from controls5 import cross_polytope, k7_minus_edge, apex_cross
    adj = {"cross": cross_polytope(), "k7me": k7_minus_edge(),
           "apex": apex_cross()}[which]
    n = {"cross": 10, "k7me": 7, "apex": 11}[which]
    st, nodes, unres = decide5(adj, n, th0=(lo, hi),
                               theta_min=theta_min, max_nodes=cap)
    return st, nodes, unres

def run_controls(pool):
    from controls5 import K
    ok = True
    # kill controls
    st, nodes, _ = decide5(K(7), 7, max_nodes=10_000_000)
    print(f"C1 K7 (expect KILLED): {st} nodes={nodes}", flush=True)
    ok &= st == "KILLED"
    st, nodes, _ = decide5(K(6), 6, max_nodes=10_000_000)
    print(f"S1 K6 (expect SURVIVORS): {st}", flush=True)
    ok &= st == "SURVIVORS"
    # apex+cross is a circle-free search: one full run must be KILLED
    st, nodes, _ = _control_slice(("apex", 0.0, TWO_PI,
                                   TWO_PI / (1 << 18), 2_000_000_000))
    print(f"C2 apex+cross-polytope (expect KILLED): {st} nodes={nodes}",
          flush=True)
    ok &= st == "KILLED"
    # survive controls: sliced; >=1 slice must report floor-width SURVIVORS
    # and no slice may be killed spuriously around the true solutions.
    # A coarse width floor keeps them cheap: the engine must simply be
    # unable to kill cells containing the true realization. (The 16-point
    # half-cube graph itself lies outside the engine's decomposition class
    # -- it admits no elimination order without a two-parameter stage --
    # so its realizability is verified separately in exact arithmetic;
    # K_7 minus an edge serves as the sphere-stage survive control.)
    NS = 24
    for which, n, tm in (("cross", 10, TWO_PI / (1 << 8)),
                         ("k7me", 7, TWO_PI / (1 << 8))):
        args = [(which, k * TWO_PI / NS, (k + 1) * TWO_PI / NS,
                 tm, 3_000_000) for k in range(NS)]
        res = pool.map(_control_slice, args)
        surv = sum(1 for st, _, _ in res if st == "SURVIVORS")
        kill = sum(1 for st, _, _ in res if st == "KILLED")
        print(f"S {which} (expect survivors>0): SURVIVORS in {surv}/{NS} "
              f"slices, KILLED {kill}, ABORT {NS - surv - kill}", flush=True)
        ok &= surv > 0
    print("controls5:", "PASS" if ok else "FAIL", flush=True)
    return ok

# ---------------------------------------------------------------------------
def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--level", type=int, default=20, choices=(17, 18, 19, 20))
    ap.add_argument("--graph", type=int, default=None)
    ap.add_argument("--from-graph", type=int, default=0)
    ap.add_argument("--to-graph", type=int, default=None)
    ap.add_argument("--controls", action="store_true")
    ap.add_argument("--shard", type=str, default=None,
                    help="k/m: process only graphs with index %% m == k "
                         "(results merged via per-shard files)")
    ap.add_argument("--bulk", action="store_true",
                    help="phase A: certify all zero-circle graphs with one "
                         "shared pool (fast); remaining graphs get the "
                         "full racing treatment")
    ap.add_argument("--workers", type=int, default=max(1, cpu_count() - 2))
    ap.add_argument("--budget", type=float, default=7200)
    args = ap.parse_args()
    ensure_kernel()
    import hashlib
    print(f"kernel: ckernel5 (sha256 "
          f"{hashlib.sha256(open('ckernel5.c','rb').read()).hexdigest()[:12]})",
          flush=True)

    if args.controls:
        with Pool(args.workers) as pool:
            sys.exit(0 if run_controls(pool) else 1)

    graphs = load_level(args.level)
    print(f"level {args.level}: {len(graphs)} graphs")
    targets = ([args.graph] if args.graph is not None
               else range(args.from_graph,
                          args.to_graph if args.to_graph is not None
                          else len(graphs)))
    shard = None
    if args.shard:
        k, m = args.shard.split("/"); shard = (int(k), int(m))
    resfile = (f"results_n{args.level}.json" if shard is None
               else f"results_n{args.level}_s{shard[0]}of{shard[1]}.json")
    results = {}
    # always seed from the main results file (skip already-certified)
    if os.path.exists(f"results_n{args.level}.json"):
        results = {int(k): v
                   for k, v in json.load(open(f"results_n{args.level}.json")).items()}
    if shard is not None and os.path.exists(resfile):
        results.update({int(k): v for k, v in json.load(open(resfile)).items()})
    t0 = time.time()
    if args.bulk:
        with Pool(args.workers) as pool:
            phase_b = bulk_certify(args.level, graphs, pool, results)
        json.dump(results, open(resfile, "w"))
        print(f"phase A done in {time.time()-t0:.0f}s; "
              f"{len(phase_b)} graphs to phase B: {phase_b[:30]}", flush=True)
        targets = phase_b
    if shard is not None:
        targets = [gi for gi in targets if gi % shard[1] == shard[0]]
        print(f"shard {shard[0]}/{shard[1]}: {len(targets)} graphs", flush=True)
    for gi in targets:
        if gi in results and results[gi] is not None:
            continue
        t = time.time()
        with Pool(args.workers) as pool:
            oi = certify_graph(args.level, gi, graphs[gi], pool,
                               budget_s=args.budget, fine=args.bulk)
        results[gi] = oi
        status = (f"CERTIFIED (dec {oi})" if oi is not None else "UNDECIDED")
        print(f"[n{args.level} {gi:5d}] {status}  t={time.time()-t:.1f}s "
              f"(total {time.time()-t0:.0f}s)", flush=True)
        json.dump(results, open(resfile, "w"))
    bad = [g for g, o in results.items() if o is None]
    done = len([g for g, o in results.items() if o is not None])
    print(f"\nlevel {args.level}: {done}/{len(graphs)} certified, "
          f"undecided: {bad if bad else 'none'}")
    if not bad and done == len(graphs):
        print(f"==> no {args.level}-point almost-equidistant set in R^5; "
              f"f(5) <= {args.level - 1}.")

if __name__ == "__main__":
    main()
