#!/usr/bin/env python3
"""Certified kill campaign for f(5): decide non-realizability in R^5 of the
minimal abstract almost-equidistant graphs on 17..20 vertices.

Top-down schedule (each completed level is a theorem):
  level 20 (8 graphs)    killed  =>  f(5) <= 19
  level 19 (340)         killed  =>  f(5) <= 18
  level 18 (8825)        killed  =>  f(5) <= 17
  level 17 (12654)       killed  =>  f(5) =  16   (with the 16-point set)

Usage:
  python reproduce5.py --controls
  python reproduce5.py --level 20 [--graph i] [--workers N]

Graph files aeq_d5_nXX.txt: one graph per line, "n mask0 ... mask{n-1}"
(complements of maximal triangle-free graphs, alpha<=2, no K7, no K333;
generated by triangleramsey + filter_mtf, counts matching BPSSV Table 2).
"""
import argparse, json, math, os, sys, time
from multiprocessing import Pool, cpu_count

from cdriver5 import decide5, gen_orders, ensure_kernel

TWO_PI = 2 * math.pi
HERE = os.path.dirname(os.path.abspath(__file__))
os.chdir(HERE)

def load_level(level):
    graphs = []
    with open(f"aeq_d5_n{level}.txt") as f:
        for line in f:
            parts = line.split()
            if not parts: continue
            n = int(parts[0]); assert n == level
            graphs.append([int(x) for x in parts[1:1 + n]])
    return graphs

# ---------------------------------------------------------------------------
_DATA = {}
def _slice_task(args):
    global _DATA
    level, gi, seed, order, lo, hi, cap = args
    if level not in _DATA:
        _DATA[level] = load_level(level)
    adj = _DATA[level][gi]
    st, nodes, unres = decide5(adj, level, seed=seed, order=list(order),
                               th0=(lo, hi), max_nodes=cap)
    return lo, hi, st, nodes

def ncirc_of(adj, n, seed, order):
    placed = set(seed); c = 0
    for v in order:
        if sum(1 for u in placed if (adj[v] >> u) & 1) == 4: c += 1
        placed.add(v)
    return c

def certify_graph(level, gi, adj, pool, max_orders=8, cap=15_000_000,
                  budget_s=7200, verbose=False):
    """Race decompositions concurrently; 8-fold split failed slices; a fully
    killed tiling certifies. Returns winning decomposition index or None."""
    import queue
    decs = gen_orders(adj, level, kmax=max_orders)
    if not decs:
        return None
    Q = queue.Queue()
    state = [{"pending": 0, "alive": True, "submitted": False} for _ in decs]
    nc0 = ncirc_of(adj, level, *decs[0])
    nslices = 768 if nc0 >= 2 else (24 if nc0 == 1 else 1)
    min_width = TWO_PI / max(nslices, 24) / 8 ** 3

    def submit_range(oi, lo, hi):
        seed, order = decs[oi]
        state[oi]["pending"] += 1
        pool.apply_async(_slice_task,
                         ((level, gi, seed, tuple(order), lo, hi, cap),),
                         callback=lambda r, oi=oi: Q.put((oi, r)),
                         error_callback=lambda e, oi=oi: Q.put((oi, e)))

    for oi in range(len(decs)):
        state[oi]["submitted"] = True
        nc = ncirc_of(adj, level, *decs[oi])
        ns = 768 if nc >= 2 else (24 if nc == 1 else 1)
        for k in range(ns):
            submit_range(oi, k * TWO_PI / ns, (k + 1) * TWO_PI / ns)
    deadline = time.time() + budget_s
    while True:
        alive = [oi for oi, s in enumerate(state) if s["alive"]]
        if not alive:
            return None
        for oi in alive:
            if state[oi]["submitted"] and state[oi]["pending"] == 0:
                return oi
        if time.time() > deadline:
            return None
        try:
            oi, r = Q.get(timeout=30)
        except Exception:
            continue
        s = state[oi]
        s["pending"] -= 1
        if isinstance(r, Exception):
            s["alive"] = False
        else:
            lo, hi, st, nodes = r
            if s["alive"] and st != "KILLED":
                if hi - lo < min_width * 8:
                    s["alive"] = False
                else:
                    w = (hi - lo) / 8
                    for k in range(8):
                        submit_range(oi, lo + k * w, lo + (k + 1) * w)

# ---------------------------------------------------------------------------
def _control_slice(args):
    which, lo, hi, theta_min, cap = args
    from controls5 import cross_polytope, halfcube16, apex_cross
    adj = {"cross": cross_polytope(), "half": halfcube16(),
           "apex": apex_cross()}[which]
    n = {"cross": 10, "half": 16, "apex": 11}[which]
    st, nodes, unres = decide5(adj, n, th0=(lo, hi),
                               theta_min=theta_min, max_nodes=cap)
    return st, nodes, unres

def run_controls(pool):
    from controls5 import K
    ok = True
    # kill controls
    st, nodes, _ = decide5(K(7), 7, max_nodes=10_000_000)
    print(f"C1 K7 (expect KILLED): {st} nodes={nodes}"); ok &= st == "KILLED"
    st, nodes, _ = decide5(K(6), 6, max_nodes=10_000_000)
    print(f"S1 K6 (expect SURVIVORS): {st}"); ok &= st == "SURVIVORS"
    # apex+cross: kill control, sliced tiling must be fully killed
    NS = 24
    args = [("apex", k * TWO_PI / NS, (k + 1) * TWO_PI / NS,
             TWO_PI / (1 << 18), 30_000_000) for k in range(NS)]
    res = pool.map(_control_slice, args)
    allk = all(st == "KILLED" for st, _, _ in res)
    print(f"C2 apex+cross-polytope 24 slices (expect all KILLED): "
          f"{sum(1 for st,_,_ in res if st=='KILLED')}/{NS} killed")
    ok &= allk
    # survive controls: >=1 slice must report SURVIVORS (never all killed)
    for which, n, tm in (("cross", 10, TWO_PI / (1 << 12)),
                         ("half", 16, TWO_PI / (1 << 10))):
        args = [(which, k * TWO_PI / NS, (k + 1) * TWO_PI / NS,
                 tm, 30_000_000) for k in range(NS)]
        res = pool.map(_control_slice, args)
        surv = sum(1 for st, _, _ in res if st == "SURVIVORS")
        kill = sum(1 for st, _, _ in res if st == "KILLED")
        print(f"S {which} (expect survivors>0): SURVIVORS in {surv}/{NS} "
              f"slices, KILLED {kill}, ABORT {NS - surv - kill}")
        ok &= surv > 0
    print("controls5:", "PASS" if ok else "FAIL")
    return ok

# ---------------------------------------------------------------------------
def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--level", type=int, default=20, choices=(17, 18, 19, 20))
    ap.add_argument("--graph", type=int, default=None)
    ap.add_argument("--from-graph", type=int, default=0)
    ap.add_argument("--to-graph", type=int, default=None)
    ap.add_argument("--controls", action="store_true")
    ap.add_argument("--workers", type=int, default=max(1, cpu_count() - 2))
    ap.add_argument("--budget", type=float, default=7200)
    args = ap.parse_args()
    ensure_kernel()
    import hashlib
    print(f"kernel: ckernel5 (sha256 "
          f"{hashlib.sha256(open('ckernel5.c','rb').read()).hexdigest()[:12]})",
          flush=True)

    if args.controls:
        with Pool(args.workers) as pool:
            sys.exit(0 if run_controls(pool) else 1)

    graphs = load_level(args.level)
    print(f"level {args.level}: {len(graphs)} graphs")
    targets = ([args.graph] if args.graph is not None
               else range(args.from_graph,
                          args.to_graph if args.to_graph is not None
                          else len(graphs)))
    resfile = f"results_n{args.level}.json"
    results = {}
    if os.path.exists(resfile):
        results = {int(k): v for k, v in json.load(open(resfile)).items()}
    t0 = time.time()
    for gi in targets:
        if gi in results and results[gi] is not None:
            continue
        t = time.time()
        with Pool(args.workers) as pool:
            oi = certify_graph(args.level, gi, graphs[gi], pool,
                               budget_s=args.budget)
        results[gi] = oi
        status = (f"CERTIFIED (dec {oi})" if oi is not None else "UNDECIDED")
        print(f"[n{args.level} {gi:5d}] {status}  t={time.time()-t:.1f}s "
              f"(total {time.time()-t0:.0f}s)", flush=True)
        json.dump(results, open(resfile, "w"))
    bad = [g for g, o in results.items() if o is None]
    done = len([g for g, o in results.items() if o is not None])
    print(f"\nlevel {args.level}: {done}/{len(graphs)} certified, "
          f"undecided: {bad if bad else 'none'}")
    if not bad and done == len(graphs):
        print(f"==> no {args.level}-point almost-equidistant set in R^5; "
              f"f(5) <= {args.level - 1}.")

if __name__ == "__main__":
    main()
